<!-- source: https://tailwindcomponents.com/component/chat-layout -->
<template>
  <IndecisionView />
</template>

<script lang="ts" setup>
import IndecisionView from '@/views/IndecisionView.vue'; /* "@/*": ["./src/*"] --> alias generated by vue configured on tsconfig.app.json */
</script>
